-- Updated: Removed age_range column
INSERT INTO quiz_questions (question_text, option_a, option_b, option_c, option_d, correct_option, points, category) VALUES
('What color do you get when you mix Red and Blue?', 'Green', 'Orange', 'Purple', 'Yellow', 2, 10, 'Educational'),
('How many legs does a spider have?', '6', '8', '10', '12', 1, 10, 'Educational'),
('Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 1, 15, 'Educational'),
('What is the largest land animal?', 'Hippopotamus', 'Elephant', 'Giraffe', 'Rhino', 1, 10, 'Educational'),
('Which toy is famous for being "More than meets the eye"?', 'Barbie', 'Transformers', 'LEGO', 'Hot Wheels', 1, 10, 'Toys'),
('How many days are in a leap year?', '364', '365', '366', '367', 2, 15, 'Educational'),
('What do bees collect from flowers to make honey?', 'Leaves', 'Water', 'Nectar', 'Mud', 2, 10, 'Educational'),
('Which of these is NOT a primary color?', 'Red', 'Blue', 'Green', 'Yellow', 2, 15, 'Educational'),
('What is the name of the toy cowboy in Toy Story?', 'Buzz Lightyear', 'Woody', 'Rex', 'Slinky', 1, 10, 'Toys'),
('How many continents are there on Earth?', '5', '6', '7', '8', 2, 15, 'Educational'),
('What is the freezing point of water?', '0°C', '32°C', '100°C', '-10°C', 0, 15, 'Educational'),
('Which animal is known as the Ship of the Desert?', 'Horse', 'Elephant', 'Camel', 'Donkey', 2, 10, 'Educational'),
('What is the tallest mountain in the world?', 'K2', 'Mount Everest', 'Kilimanjaro', 'Fuji', 1, 15, 'Educational'),
('Which fruit is known for having its seeds on the outside?', 'Apple', 'Banana', 'Strawberry', 'Orange', 2, 15, 'Educational'),
('How many colors are in a rainbow?', '5', '6', '7', '8', 2, 10, 'Educational'),
('Who painted the Mona Lisa?', 'Van Gogh', 'Picasso', 'Leonardo da Vinci', 'Claude Monet', 2, 20, 'Educational'),
('What gas do plants absorb from the atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 1, 15, 'Educational'),
('Which toy consists of interlocking plastic bricks?', 'K-Nex', 'Meccano', 'LEGO', 'Play-Doh', 2, 10, 'Toys'),
('What is the capital of France?', 'London', 'Berlin', 'Paris', 'Rome', 2, 15, 'Educational'),
('How many hours are in a full day?', '12', '24', '48', '60', 1, 10, 'Educational'),
('What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Stone', 2, 15, 'Educational'),
('Which bird cannot fly?', 'Eagle', 'Ostrich', 'Parrot', 'Sparrow', 1, 10, 'Educational'),
('What is the smallest planet in our solar system?', 'Mars', 'Earth', 'Mercury', 'Venus', 2, 15, 'Educational'),
('Which shape has three sides?', 'Square', 'Rectangle', 'Triangle', 'Circle', 2, 10, 'Educational'),
('What is a baby frog called?', 'Cub', 'Fry', 'Tadpole', 'Chick', 2, 10, 'Educational'),
('How many zeros are in one thousand?', '2', '3', '4', '5', 1, 10, 'Educational'),
('Which ocean is the largest?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 3, 15, 'Educational'),
('What is the name of the fairy in Peter Pan?', 'Cinderella', 'Tinker Bell', 'Belle', 'Ariel', 1, 10, 'Toys'),
('How many sides does an octagon have?', '6', '7', '8', '10', 2, 15, 'Educational'),
('What do you call a person who travels to space?', 'Pilot', 'Sailor', 'Astronaut', 'Driver', 2, 10, 'Educational'),
('Which sense do you use to hear music?', 'Sight', 'Touch', 'Hearing', 'Smell', 2, 10, 'Educational'),
('What is the fastest land animal?', 'Cheetah', 'Lion', 'Tiger', 'Horse', 0, 10, 'Educational'),
('In which season do leaves fall from trees?', 'Spring', 'Summer', 'Autumn', 'Winter', 2, 10, 'Educational'),
('Which planet has beautiful rings around it?', 'Mars', 'Saturn', 'Neptune', 'Earth', 1, 10, 'Educational'),
('What is the name of the Grinch’s dog?', 'Max', 'Buddy', 'Charlie', 'Rocky', 0, 10, 'Educational'),
('How many bones are in the adult human body?', '106', '206', '306', '406', 1, 20, 'Educational'),
('Which board game involves buying properties and houses?', 'Chess', 'Checkers', 'Monopoly', 'Scrabble', 2, 10, 'Toys'),
('What is the main ingredient in chocolate?', 'Sugar', 'Milk', 'Cocoa Beans', 'Flour', 2, 15, 'Educational'),
('Which instrument has 88 keys?', 'Guitar', 'Violin', 'Piano', 'Flute', 2, 15, 'Educational'),
('What is the name of the snowman in Frozen?', 'Sven', 'Kristoff', 'Olaf', 'Hans', 2, 10, 'Toys'),
('Which country is home to the Kangaroo?', 'USA', 'India', 'Australia', 'Brazil', 2, 10, 'Educational'),
('What is the closest star to Earth?', 'Polaris', 'Sirius', 'The Sun', 'Alpha Centauri', 2, 15, 'Educational'),
('How many years are in a decade?', '10', '50', '100', '1000', 0, 10, 'Educational'),
('Which toy brand is famous for its die-cast cars?', 'Barbie', 'Hot Wheels', 'Nerf', 'Fisher-Price', 1, 10, 'Toys'),
('What is the chemical symbol for water?', 'CO2', 'O2', 'H2O', 'NaCl', 2, 15, 'Educational'),
('Which animal is known to be the "King of the Jungle"?', 'Tiger', 'Elephant', 'Lion', 'Bear', 2, 10, 'Educational'),
('What do we use to measure temperature?', 'Ruler', 'Scale', 'Thermometer', 'Clock', 2, 10, 'Educational'),
('Which planet is the largest in our solar system?', 'Earth', 'Saturn', 'Jupiter', 'Neptune', 2, 15, 'Educational'),
('What is the primary food for pandas?', 'Eucalyptus', 'Bamboo', 'Fish', 'Grass', 1, 15, 'Educational'),
('How many players are on a soccer team on the field?', '9', '10', '11', '12', 2, 15, 'Educational');




INSERT INTO products (name, price, category, age_range, image_url, is_featured) VALUES
('Eco-Friendly Rattle', 499.00, 'activity-toys', '0-2', '/images/ages/age-0-2.jpg', TRUE),
('Alphabet Wooden Puzzle', 899.00, 'puzzles', '2-4', '/images/ages/age-2-4.jpg', TRUE),
('Junior STEM Kit', 1299.00, 'activity-toys', '4-6', '/images/ages/age-4-6.jpg', FALSE),
('Magnetic Building Blocks', 1599.00, 'wooden-toys', '6+', '/images/ages/age-6.jpg', TRUE),
('Colorful Xylophone', 650.00, 'activity-toys', '0-2', '/images/ages/age-0-2.jpg', FALSE),
('Memory Match Game', 350.00, 'indoor-games', '4-6', '/images/products/memory.jpg', FALSE);